local Panel = {}
Panel.__index = Panel

local ctx = ...
if not ctx then
    warn("[LoaderPanel] ctx not provided")
    return Panel
end

local Inject = ctx.Inject
local Render = ctx.Render

if Render and Render.new then
    local r = Render.new({ Name = "LoaderPanel_Render" })

    r:Rect({
        Pos = Vector2.new(20, 60),
        Size = Vector2.new(220, 90),
        Filled = false,
        Thickness = 2,
        Radius = 12,
        Color = Color3.fromRGB(120, 90, 255),
    })

    r:Text({
        Pos = Vector2.new(34, 88),
        Size = Vector2.new(200, 20),
        Text = "ctx.Render работает",
        Outline = true,
    })
end



--local Players = game:GetService("Players")
--local TweenService = game:GetService("TweenService")
--local UserInputService = game:GetService("UserInputService")
--
--local lp = Players.LocalPlayer
--
--local Panel = {}
--Panel.__index = Panel
--
--local THEME = {
--    Bg = Color3.fromRGB(12, 12, 16),
--    Panel = Color3.fromRGB(22, 22, 30),
--    Panel2 = Color3.fromRGB(28, 28, 38),
--    Stroke = Color3.fromRGB(70, 70, 90),
--    Text = Color3.fromRGB(240, 240, 245),
--    Muted = Color3.fromRGB(165, 165, 185),
--    Accent = Color3.fromRGB(120, 90, 255),
--    Good = Color3.fromRGB(80, 210, 120),
--    Bad = Color3.fromRGB(235, 85, 100),
--}
--
--local function corner(r, parent)
--    local c = Instance.new("UICorner")
--    c.CornerRadius = UDim.new(0, r)
--    c.Parent = parent
--    return c
--end
--
--local function stroke(parent, t)
--    local s = Instance.new("UIStroke")
--    s.Color = THEME.Stroke
--    s.Thickness = t or 1
--    s.Transparency = 0.35
--    s.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
--    s.Parent = parent
--    return s
--end
--
--local function pad(parent, p)
--    local u = Instance.new("UIPadding")
--    u.PaddingTop = UDim.new(0, p)
--    u.PaddingBottom = UDim.new(0, p)
--    u.PaddingLeft = UDim.new(0, p)
--    u.PaddingRight = UDim.new(0, p)
--    u.Parent = parent
--    return u
--end
--
--local function tween(o, ti, props)
--    local t = TweenService:Create(o, ti, props)
--    t:Play()
--    return t
--end
--
--local function mkText(parent, text, size, bold, muted)
--    local l = Instance.new("TextLabel")
--    l.BackgroundTransparency = 1
--    l.Text = text or ""
--    l.Font = bold and Enum.Font.GothamBold or Enum.Font.Gotham
--    l.TextSize = size or 14
--    l.TextColor3 = muted and THEME.Muted or THEME.Text
--    l.TextXAlignment = Enum.TextXAlignment.Left
--    l.TextYAlignment = Enum.TextYAlignment.Center
--    l.Parent = parent
--    return l
--end
--
--local function mkBtn(parent, text)
--    local b = Instance.new("TextButton")
--    b.AutoButtonColor = false
--    b.Text = text or "Button"
--    b.Font = Enum.Font.GothamBold
--    b.TextSize = 14
--    b.TextColor3 = THEME.Text
--    b.BackgroundColor3 = Color3.fromRGB(35, 35, 48)
--    b.Parent = parent
--    corner(10, b)
--    return b
--end
--
--local function mkBox(parent, placeholder)
--    local tb = Instance.new("TextBox")
--    tb.ClearTextOnFocus = false
--    tb.Text = ""
--    tb.PlaceholderText = placeholder or ""
--    tb.Font = Enum.Font.Gotham
--    tb.TextSize = 14
--    tb.TextColor3 = THEME.Text
--    tb.PlaceholderColor3 = THEME.Muted
--    tb.BackgroundColor3 = Color3.fromRGB(30, 30, 42)
--    tb.Parent = parent
--    corner(10, tb)
--    return tb
--end
--
--local function safeParent(gui)
--    local ok = pcall(function()
--        gui.Parent = game:GetService("CoreGui")
--    end)
--    if ok then return end
--
--    if lp then
--        local pg = lp:FindFirstChildOfClass("PlayerGui")
--        if pg then
--            gui.Parent = pg
--            return
--        end
--    end
--
--    gui.Parent = game:GetService("StarterGui")
--end
--
--function Panel.new()
--    local self = setmetatable({}, Panel)
--
--    local gui = Instance.new("ScreenGui")
--    gui.Name = "Heaven_LoaderPanel"
--    gui.ResetOnSpawn = false
--    gui.IgnoreGuiInset = true
--    gui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
--    safeParent(gui)
--    self.Gui = gui
--
--    local overlay = Instance.new("Frame")
--    overlay.Size = UDim2.fromScale(1, 1)
--    overlay.BackgroundColor3 = Color3.new(0, 0, 0)
--    overlay.BackgroundTransparency = 1
--    overlay.Parent = gui
--    self.Overlay = overlay
--
--    local frame = Instance.new("Frame")
--    frame.AnchorPoint = Vector2.new(0.5, 0.5)
--    frame.Position = UDim2.fromScale(0.5, 0.5)
--    frame.Size = UDim2.fromOffset(560, 330)
--    frame.BackgroundColor3 = THEME.Panel
--    frame.BackgroundTransparency = 1
--    frame.Parent = overlay
--    corner(16, frame)
--    stroke(frame, 1)
--    self.Frame = frame
--
--    -- Top bar
--    local top = Instance.new("Frame")
--    top.Size = UDim2.new(1, 0, 0, 56)
--    top.BackgroundColor3 = THEME.Panel2
--    top.Parent = frame
--    corner(16, top)
--    stroke(top, 1)
--    pad(top, 14)
--
--    local title = mkText(top, "Unknown Heaven", 18, true, false)
--    title.Size = UDim2.new(1, -120, 0, 22)
--    title.Position = UDim2.fromOffset(0, 6)
--
--    local subtitle = mkText(top, "Loader Panel", 13, false, true)
--    subtitle.Size = UDim2.new(1, -120, 0, 18)
--    subtitle.Position = UDim2.fromOffset(0, 28)
--
--    local close = mkBtn(top, "✕")
--    close.Size = UDim2.fromOffset(42, 32)
--    close.Position = UDim2.new(1, -42, 0, 10)
--    close.BackgroundColor3 = Color3.fromRGB(55, 25, 35)
--
--    -- Content
--    local body = Instance.new("Frame")
--    body.BackgroundTransparency = 1
--    body.Position = UDim2.fromOffset(0, 56)
--    body.Size = UDim2.new(1, 0, 1, -56)
--    body.Parent = frame
--    pad(body, 14)
--
--    local left = Instance.new("Frame")
--    left.Size = UDim2.new(0, 160, 1, 0)
--    left.BackgroundColor3 = THEME.Panel2
--    left.Parent = body
--    corner(14, left)
--    stroke(left, 1)
--    pad(left, 12)
--
--    local right = Instance.new("Frame")
--    right.Position = UDim2.new(0, 170, 0, 0)
--    right.Size = UDim2.new(1, -170, 1, 0)
--    right.BackgroundColor3 = THEME.Panel2
--    right.Parent = body
--    corner(14, right)
--    stroke(right, 1)
--    pad(right, 14)
--
--    local list = Instance.new("UIListLayout")
--    list.Padding = UDim.new(0, 8)
--    list.SortOrder = Enum.SortOrder.LayoutOrder
--    list.Parent = left
--
--    local logo = mkText(left, "Heaven", 14, true, false)
--    logo.TextColor3 = THEME.Accent
--    logo.Size = UDim2.new(1, 0, 0, 18)
--    logo.LayoutOrder = 0
--
--    local btnHome = mkBtn(left, "Home")
--    btnHome.Size = UDim2.new(1, 0, 0, 34)
--    btnHome.LayoutOrder = 1
--
--    local btnSettings = mkBtn(left, "Settings")
--    btnSettings.Size = UDim2.new(1, 0, 0, 34)
--    btnSettings.LayoutOrder = 2
--
--    local btnAbout = mkBtn(left, "About")
--    btnAbout.Size = UDim2.new(1, 0, 0, 34)
--    btnAbout.LayoutOrder = 3
--
--    local pages = Instance.new("Folder")
--    pages.Parent = right
--    self.Pages = pages
--
--    local function mkPage(name)
--        local p = Instance.new("Frame")
--        p.Name = name
--        p.BackgroundTransparency = 1
--        p.Size = UDim2.fromScale(1, 1)
--        p.Visible = false
--        p.Parent = pages
--        return p
--    end
--
--    local pHome = mkPage("Home")
--    local pSet = mkPage("Settings")
--    local pAbt = mkPage("About")
--
--    local function show(p)
--        for _, ch in ipairs(pages:GetChildren()) do
--            ch.Visible = (ch == p)
--        end
--    end
--
--    local function active(btn, on)
--        btn.BackgroundColor3 = on and THEME.Accent or Color3.fromRGB(35, 35, 48)
--    end
--
--    local function nav(name)
--        if name == "Home" then
--            show(pHome); active(btnHome, true); active(btnSettings, false); active(btnAbout, false)
--        elseif name == "Settings" then
--            show(pSet); active(btnHome, false); active(btnSettings, true); active(btnAbout, false)
--        else
--            show(pAbt); active(btnHome, false); active(btnSettings, false); active(btnAbout, true)
--        end
--    end
--
--    -- HOME page content
--    local h1 = mkText(pHome, "Ready to load", 18, true, false)
--    h1.Size = UDim2.new(1, 0, 0, 24)
--
--    local h2 = mkText(pHome, "Нажми Load чтобы продолжить.", 13, false, true)
--    h2.Size = UDim2.new(1, 0, 0, 20)
--    h2.Position = UDim2.fromOffset(0, 26)
--
--    local keyLbl = mkText(pHome, "Key (optional)", 13, true, true)
--    keyLbl.Size = UDim2.new(1, 0, 0, 18)
--    keyLbl.Position = UDim2.fromOffset(0, 62)
--
--    local keyBox = mkBox(pHome, "Enter key... (optional)")
--    keyBox.Size = UDim2.new(1, 0, 0, 38)
--    keyBox.Position = UDim2.fromOffset(0, 84)
--
--    local status = mkText(pHome, "Status: Idle", 13, false, true)
--    status.Size = UDim2.new(1, 0, 0, 18)
--    status.Position = UDim2.fromOffset(0, 130)
--
--    local row = Instance.new("Frame")
--    row.BackgroundTransparency = 1
--    row.Size = UDim2.new(1, 0, 0, 40)
--    row.Position = UDim2.fromOffset(0, 160)
--    row.Parent = pHome
--
--    local load = mkBtn(row, "Load")
--    load.Size = UDim2.new(0.5, -6, 1, 0)
--    load.BackgroundColor3 = THEME.Accent
--
--    local hide = mkBtn(row, "Hide")
--    hide.Size = UDim2.new(0.5, -6, 1, 0)
--    hide.Position = UDim2.new(0.5, 6, 0, 0)
--
--    local function setStatus(text, mode)
--        status.Text = "Status: " .. text
--        if mode == "good" then
--            status.TextColor3 = THEME.Good
--        elseif mode == "bad" then
--            status.TextColor3 = THEME.Bad
--        else
--            status.TextColor3 = THEME.Muted
--        end
--    end
--
--    -- Settings / About placeholder
--    do
--        local s1 = mkText(pSet, "Settings", 18, true, false)
--        s1.Size = UDim2.new(1, 0, 0, 24)
--
--        local s2 = mkText(pSet, "Тут потом будут настройки.", 13, false, true)
--        s2.Size = UDim2.new(1, 0, 0, 20)
--        s2.Position = UDim2.fromOffset(0, 28)
--
--        local a1 = mkText(pAbt, "About", 18, true, false)
--        a1.Size = UDim2.new(1, 0, 0, 24)
--
--        local a2 = mkText(pAbt, "Unknown Heaven loader panel UI.", 13, false, true)
--        a2.Size = UDim2.new(1, 0, 0, 20)
--        a2.Position = UDim2.fromOffset(0, 28)
--    end
--
--    -- Навигация
--    btnHome.MouseButton1Click:Connect(function() nav("Home") end)
--    btnSettings.MouseButton1Click:Connect(function() nav("Settings") end)
--    btnAbout.MouseButton1Click:Connect(function() nav("About") end)
--    nav("Home")
--
--    -- Действия
--    load.MouseButton1Click:Connect(function()
--        setStatus("Loading...", nil)
--
--        -- сюда потом поставишь загрузку следующего файла
--        -- пример:
--        -- inject:Load("source/Main/Gui/GuiRenderer.lua")
--
--        task.wait(0.15)
--        setStatus("Loaded", "good")
--    end)
--
--    hide.MouseButton1Click:Connect(function()
--        gui.Enabled = false
--    end)
--
--    close.MouseButton1Click:Connect(function()
--        gui:Destroy()
--    end)
--
--    -- ESC скрыть
--    self._esc = UserInputService.InputBegan:Connect(function(inp, gp)
--        if gp then return end
--        if inp.KeyCode == Enum.KeyCode.Escape then
--            gui.Enabled = false
--        end
--    end)
--
--    -- Анимация появления
--    overlay.BackgroundTransparency = 1
--    tween(overlay, TweenInfo.new(0.18, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {BackgroundTransparency = 0.35})
--    tween(frame, TweenInfo.new(0.18, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {BackgroundTransparency = 0})
--
--    return self
--end
--
--function Panel:Destroy()
--    if self._esc then self._esc:Disconnect() end
--    if self.Gui then self.Gui:Destroy() end
--end
--
--local instance = Panel.new()
--
--return {
--    Instance = instance,
--    Destroy = function() instance:Destroy() end
--}
